name: geolocator_floss
description: Geolocation plugin for Flutter using only FLOSS dependencies. Forked from baseflow/flutter-geolocator_floss
repository: https://github.com/tankste/flutter-geolocator-floss/tree/main/geolocator
issue_tracker: https://github.com/tankste/flutter-geolocator-floss/issues
version: 0.1.0

environment:
  sdk: ^3.5.0
  flutter: ">=2.8.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: geolocator_floss_android

dependencies:
  flutter:
    sdk: flutter

  geolocator_floss_platform_interface: ^0.1.0
  geolocator_floss_android: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.0.0-nullsafety.7
  plugin_platform_interface: ^2.1.8
